/*PROBLEM 1*/
SELECT TITLE, RETAIL 
FROM BOOKS 
WHERE RETAIL < (SELECT AVG(RETAIL) FROM BOOKS);

/*PROBLEM 2*/
SELECT TITLE, CATEGORY, COST
FROM BOOKS B 
WHERE COST < (SELECT AVG(COST) FROM BOOKS GROUP BY CATEGORY HAVING CATEGORY = B.CATEGORY);

/*PROBLEM 3*/
SELECT ORDER#, SHIPSTATE 
FROM ORDERS
WHERE SHIPSTATE = (SELECT SHIPSTATE FROM ORDERS WHERE ORDER# = 1014);

/*PROBLEM 4*/
SELECT O.ORDER#, O.SHIPCOST + OI.PAIDEACH AS TOTAL
FROM ORDERS O
JOIN ORDERITEMS OI ON O.ORDER# = OI.ORDER#
WHERE (OI.QUANTITY*OI.PAIDEACH + O.SHIPCOST) >
(SELECT OI.QUANTITY*OI.PAIDEACH + O.SHIPCOST
    FROM ORDERS O
    JOIN ORDERITEMS OI ON O.ORDER# = OI.ORDER#
    WHERE OI.ORDER# = 1008);

/*PROBLEM 5*/
SELECT A.FNAME, A.LNAME
FROM BOOKAUTHOR BA
JOIN AUTHOR A ON BA.AUTHORID = A.AUTHORID
WHERE ISBN IN (SELECT ISBN FROM ORDERITEMS GROUP BY ISBN HAVING SUM(QUANTITY) =
(SELECT MAX(COUNT(QUANTITY)) FROM ORDERITEMS GROUP BY ISBN));

/*PROBLEM 6*/
SELECT TITLE
FROM BOOKS
WHERE CATEGORY IN(SELECT DISTINCT CATEGORY
FROM BOOKS B JOIN ORDERITEMS OI ON B.ISBN = OI.ISBN
JOIN ORDERS O ON OI.ORDER# = O.ORDER#
WHERE O.CUSTOMER# = 1007)
AND ISBN NOT IN (SELECT ISBN
FROM ORDERS O JOIN ORDERITEMS OI ON O.ORDER# = OI.ORDER#
WHERE O.CUSTOMER# = 1007);

/*PROBLEM 7*/
SELECT SHIPCITY, SHIPSTATE
FROM ORDERS
WHERE SHIPDATE - ORDERDATE =
(SELECT MAX(SHIPDATE - ORDERDATE)
FROM ORDERS);

/*PROBLEM 8*/
SELECT C.CUSTOMER#
FROM CUSTOMERS C JOIN ORDERS O ON C.CUSTOMER# = O.CUSTOMER# 
JOIN ORDERITEMS OI ON OI.ORDER# = O.ORDER#
JOIN BOOKS B ON B.ISBN = OI.ISBN
WHERE RETAIL = (SELECT MIN(RETAIL)
FROM BOOKS);

/*PROBLEM 9*/
SELECT COUNT(DISTINCT C.CUSTOMER#) AS DIFFERENT_CUSTOMERS
FROM CUSTOMERS C
JOIN ORDERS O ON C.CUSTOMER# = O.CUSTOMER#
JOIN ORDERITEMS OI ON O.ORDER# = OI.ORDER#
WHERE ISBN IN (SELECT BA.ISBN FROM BOOKAUTHOR BA JOIN ORDERITEMS OI ON BA.ISBN = OI.ISBN
                AND BA.AUTHORID = 'A100');

/*PROBLEM 10*/
SELECT TITLE
FROM BOOKS
WHERE PUBID IN (SELECT PUBID FROM BOOKS WHERE TITLE = 'THE WOK WAY TO COOK');









