DROP SEQUENCE ADD_CUSTOMER;
DROP SEQUENCE MY_FIRST_SEQ;
DROP INDEX CUSTOMERS_BITMAP;

/*PROBLEM 1*/
CREATE SEQUENCE ADD_CUSTOMER
START WITH 1021
INCREMENT BY 1;

/*PROBLEM 2*/
INSERT INTO CUSTOMERS (CUSTOMER#, LASTNAME, FIRSTNAME, ZIP)
VALUES (ADD_CUSTOMER.NEXTVAL, 'SHOULDERS', 'FRANK', '23567');

/*PROBLEM 3*/
CREATE SEQUENCE MY_FIRST_SEQ
START WITH 5
INCREMENT BY -3
MAXVALUE 5
MINVALUE 0
NOCYCLE;

/*PROBLEM 4*/
SELECT MY_FIRST_SEQ.NEXTVAL FROM DUAL;
SELECT MY_FIRST_SEQ.NEXTVAL FROM DUAL;
SELECT MY_FIRST_SEQ.NEXTVAL FROM DUAL;

/*PROBLEM 5*/
ALTER SEQUENCE MY_FIRST_SEQ
MINVALUE -1000;

/*PROBLEM 9*/
CREATE BITMAP INDEX CUSTOMERS_BITMAP ON CUSTOMERS(STATE);

SELECT INDEX_NAME FROM USER_INDEXES;

DROP INDEX CUSTOMERS_BITMAP;



